import "./globals.css";

import type { Metadata } from "next";
import localFont from "next/font/local";

import RootProvider from "@/components/common/root-provider";
import { cn } from "@/utils/cn";

const pretendard = localFont({
  src: "../fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
  display: "swap",
});

const gowunDodum = localFont({
  src: "../fonts/GowunDodum-Regular.ttf",
  variable: "--font-gowun-dodum",
  display: "swap",
});

const kotraHope = localFont({
  src: "../fonts/KOTRA-HOPE.ttf",
  variable: "--font-kotra-hope",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={cn("antialiased", gowunDodum.className, pretendard.variable, kotraHope.variable)}
      >
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
